
volumes:
  postgres:
    driver: local
  redis:
    external: false
  superset_data:
    external: false

networks:
  my_network:
    driver: bridge


x-superset-user: &superset-user root
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  # - ./superset:/app/superset
  - ./docker/superset_config.py:/app/pythonpath/superset_config.py


services:

  pgdatabase:
    image: postgres:16
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: db_etl_dev
    ports:
     - "5437:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
      - ./postgres/superset_init.sql:/docker-entrypoint-initdb.d/superset_init.sql
    networks:
      - my_network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8087:80"
    networks:
      - my_network    


  airflow:
    image: apache/airflow:3.1.5
    container_name: airflow
    ports:
      - "8097:8080" 
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@pgdatabase:5432/db_airflow
      PYTHONPATH: /opt/airflow
    volumes:
      - ./etl_workflow/dags:/opt/airflow/dags
      - ./etl_workflow/logs:/opt/airflow/logs
      - ./etl_ingestion:/opt/airflow/etl_ingestion
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - pgdatabase 
    networks:
      - my_network
    command: >
      bash -c "airflow db migrate && airflow standalone"
    env_file:
      - .env


  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    container_name: dbt
    volumes:
      - ./etl_transform/dev_dbt:/usr/app
      - ./etl_transform:/root/.etl_transform
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.etl_transform"
    depends_on:
      - pgdatabase
    networks:
      - my_network
    command: run


  superset:
    env_file:
      - path: /docker/.env # default
        required: true
    image: apache/superset:3.0.0-py310
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app"]
    restart: unless-stopped
    ports:
      - 8088:8088
    user: *superset-user
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      DATABASE_DB: "db_superset"
      DATABASE_HOST: pgdatabase
      EXAMPLES_HOST: pgdatabase
    networks:
      - my_network



  superset-init:
    image: apache/superset:3.0.0-py310
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - path: /docker/.env # default
        required: true
    depends_on:
      pgdatabase:
        condition: service_started
      redis:
        condition: service_started
    user: *superset-user
    volumes: *superset-volumes
    environment:
      # SUPERSET_LOAD_EXAMPLES: "{SUPERSET_LOAD_EXAMPLES}"
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      DATABASE_DB: "db_superset"
      DATABASE_HOST: pgdatabase
      EXAMPLES_HOST: pgdatabase
    healthcheck:
      disable: true
    networks: 
      - my_network
      


  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data
    networks:
      - my_network